-- MySQL Script generated by MySQL Workbench
-- Mon Sep  2 00:08:55 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ambardb_model
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ambardb_model` ;

-- -----------------------------------------------------
-- Schema ambardb_model
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ambardb_model` DEFAULT CHARACTER SET utf8 ;
USE `ambardb_model` ;

-- -----------------------------------------------------
-- Table `ambardb_model`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ambardb_model`.`product` ;

CREATE TABLE IF NOT EXISTS `ambardb_model`.`product` (
  `prod_id` INT(11) NOT NULL AUTO_INCREMENT,
  `prod_imgUrl` VARCHAR(250) NOT NULL,
  `prod_title` VARCHAR(250) NOT NULL,
  `prod_stockAmount` VARCHAR(2) NOT NULL,
  `prod_price` VARCHAR(7) NOT NULL,
  `prod_discount` VARCHAR(3) NULL DEFAULT NULL,
  PRIMARY KEY (`prod_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `ambardb_model`.`buyedproducts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ambardb_model`.`buyedproducts` ;



-- -----------------------------------------------------
-- Table `ambardb_model`.`city`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ambardb_model`.`city` ;

CREATE TABLE IF NOT EXISTS `ambardb_model`.`city` (
  `city_id` INT(11) NOT NULL AUTO_INCREMENT,
  `city_name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`city_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `ambardb_model`.`colors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ambardb_model`.`colors` ;

CREATE TABLE IF NOT EXISTS `ambardb_model`.`colors` (
  `color_id` INT(11) NOT NULL AUTO_INCREMENT,
  `color_name` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`color_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `ambardb_model`.`complain`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ambardb_model`.`complain` ;

CREATE TABLE IF NOT EXISTS `ambardb_model`.`complain` (
  `complain_id` INT(11) NOT NULL AUTO_INCREMENT,
  `complain_category` INT(11) NOT NULL,
  `complain_text` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`complain_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `ambardb_model`.`condition`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ambardb_model`.`condition` ;

CREATE TABLE IF NOT EXISTS `ambardb_model`.`condition` (
  `condition_id` INT(11) NOT NULL AUTO_INCREMENT,
  `condition_name` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`condition_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `ambardb_model`.`country`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ambardb_model`.`country` ;

CREATE TABLE IF NOT EXISTS `ambardb_model`.`country` (
  `country_id` INT(11) NOT NULL AUTO_INCREMENT,
  `country_name` TEXT NOT NULL,
  PRIMARY KEY (`country_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `ambardb_model`.`maker`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ambardb_model`.`maker` ;

CREATE TABLE IF NOT EXISTS `ambardb_model`.`maker` (
  `maker_id` INT(11) NOT NULL AUTO_INCREMENT,
  `maker_name` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`maker_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `ambardb_model`.`model`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ambardb_model`.`model` ;

CREATE TABLE IF NOT EXISTS `ambardb_model`.`model` (
  `model_id` INT(11) NOT NULL AUTO_INCREMENT,
  `model_name` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`model_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `ambardb_model`.`power`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ambardb_model`.`power` ;

CREATE TABLE IF NOT EXISTS `ambardb_model`.`power` (
  `power_id` INT(11) NOT NULL AUTO_INCREMENT,
  `power_def` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`power_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `ambardb_model`.`size`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ambardb_model`.`size` ;

CREATE TABLE IF NOT EXISTS `ambardb_model`.`size` (
  `size_id` INT(11) NOT NULL AUTO_INCREMENT,
  `size_def` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`size_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `ambardb_model`.`state`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ambardb_model`.`state` ;

CREATE TABLE IF NOT EXISTS `ambardb_model`.`state` (
  `state_id` INT(11) NOT NULL AUTO_INCREMENT,
  `state_name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`state_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `ambardb_model`.`storage`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ambardb_model`.`storage` ;

CREATE TABLE IF NOT EXISTS `ambardb_model`.`storage` (
  `storage_id` INT(11) NOT NULL AUTO_INCREMENT,
  `storage_def` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`storage_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `ambardb_model`.`address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ambardb_model`.`address` ;

CREATE TABLE IF NOT EXISTS `ambardb_model`.`address` (
  `address_id` INT(11) NOT NULL AUTO_INCREMENT,
  `address_streetName` VARCHAR(255) NOT NULL,
  `address_number` VARCHAR(15) NOT NULL,
  `address_district` VARCHAR(50) NOT NULL,
  `address_cep` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`address_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `ambardb_model`.`store`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ambardb_model`.`store` ;

CREATE TABLE IF NOT EXISTS `ambardb_model`.`store` (
  `store_id` INT(11) NOT NULL AUTO_INCREMENT,
  `store_name` VARCHAR(30) NOT NULL,
  `store_cnpj` CHAR(14) NOT NULL,
  `store_phone` CHAR(10) NOT NULL,
  `store_cellphone` CHAR(11) NOT NULL,
  `address_id` INT(11) NULL DEFAULT NULL,
  `product_prod_id` INT(11) NOT NULL,
  PRIMARY KEY (`store_id`, `product_prod_id`),
  UNIQUE INDEX `store_name` (`store_name` ASC),
  INDEX `store_address` (`address_id` ASC),
  INDEX `fk_store_product1_idx` (`product_prod_id` ASC),
  CONSTRAINT `store_address`
    FOREIGN KEY (`address_id`)
    REFERENCES `ambardb_model`.`address` (`address_id`),
  CONSTRAINT `fk_store_product1`
    FOREIGN KEY (`product_prod_id`)
    REFERENCES `ambardb_model`.`product` (`prod_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `ambardb_model`.`usrdetail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ambardb_model`.`usrdetail` ;

CREATE TABLE IF NOT EXISTS `ambardb_model`.`usrdetail` (
  `usrDetail_id` INT(11) NOT NULL AUTO_INCREMENT,
  `usrDetail_firstPhone` VARCHAR(15) NOT NULL,
  `usrDetail_secondPhone` VARCHAR(15) NULL DEFAULT NULL,
  `usrDetail_birthday` DATE NOT NULL,
  `usrDetail_cpf` INT(12) NOT NULL,
  PRIMARY KEY (`usrDetail_id`),
  UNIQUE INDEX `usrDetail_firstPhone` (`usrDetail_firstPhone` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `ambardb_model`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ambardb_model`.`user` ;

CREATE TABLE IF NOT EXISTS `ambardb_model`.`user` (
  `usr_id` INT(11) NOT NULL AUTO_INCREMENT,
  `usr_name` VARCHAR(30) NOT NULL,
  `usr_email` VARCHAR(50) NOT NULL,
  `usr_password` VARCHAR(255) NOT NULL,
  `prod_id` INT(11) NULL DEFAULT NULL,
  `usrDetail_id` INT(11) NULL DEFAULT NULL,
  `product_prod_id` INT(11) NOT NULL,
  PRIMARY KEY (`usr_id`, `product_prod_id`),
  UNIQUE INDEX `usr_email` (`usr_email` ASC) ,
  UNIQUE INDEX `usr_password` (`usr_password` ASC) ,
  INDEX `usr_detail` (`usrDetail_id` ASC) ,
  INDEX `fk_user_product1_idx` (`product_prod_id` ASC) ,
  CONSTRAINT `usr_detail`
    FOREIGN KEY (`usrDetail_id`)
    REFERENCES `ambardb_model`.`usrdetail` (`usrDetail_id`),
  CONSTRAINT `fk_user_product1`
    FOREIGN KEY (`product_prod_id`)
    REFERENCES `ambardb_model`.`product` (`prod_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `ambardb_model`.`versions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ambardb_model`.`versions` ;

CREATE TABLE IF NOT EXISTS `ambardb_model`.`versions` (
  `vers_id` INT(11) NOT NULL AUTO_INCREMENT,
  `vers_name` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`vers_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `ambardb_model`.`voltage`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ambardb_model`.`voltage` ;

CREATE TABLE IF NOT EXISTS `ambardb_model`.`voltage` (
  `voltage_id` INT(11) NOT NULL AUTO_INCREMENT,
  `voltage_def` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`voltage_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `ambardb_model`.`product_has_colors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ambardb_model`.`product_has_colors` ;

CREATE TABLE IF NOT EXISTS `ambardb_model`.`product_has_colors` (
  `product_prod_id` INT(11) NOT NULL,
  `colors_color_id` INT(11) NOT NULL,
  PRIMARY KEY (`product_prod_id`, `colors_color_id`),
  INDEX `fk_product_has_colors_colors1_idx` (`colors_color_id` ASC) ,
  INDEX `fk_product_has_colors_product1_idx` (`product_prod_id` ASC) ,
  CONSTRAINT `fk_product_has_colors_product1`
    FOREIGN KEY (`product_prod_id`)
    REFERENCES `ambardb_model`.`product` (`prod_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_has_colors_colors1`
    FOREIGN KEY (`colors_color_id`)
    REFERENCES `ambardb_model`.`colors` (`color_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `ambardb_model`.`product_has_maker`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ambardb_model`.`product_has_maker` ;

CREATE TABLE IF NOT EXISTS `ambardb_model`.`product_has_maker` (
  `product_prod_id` INT(11) NOT NULL,
  `maker_maker_id` INT(11) NOT NULL,
  PRIMARY KEY (`product_prod_id`, `maker_maker_id`),
  INDEX `fk_product_has_maker_maker1_idx` (`maker_maker_id` ASC) ,
  INDEX `fk_product_has_maker_product1_idx` (`product_prod_id` ASC) ,
  CONSTRAINT `fk_product_has_maker_product1`
    FOREIGN KEY (`product_prod_id`)
    REFERENCES `ambardb_model`.`product` (`prod_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_has_maker_maker1`
    FOREIGN KEY (`maker_maker_id`)
    REFERENCES `ambardb_model`.`maker` (`maker_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `ambardb_model`.`product_has_condition`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ambardb_model`.`product_has_condition` ;

CREATE TABLE IF NOT EXISTS `ambardb_model`.`product_has_condition` (
  `product_prod_id` INT(11) NOT NULL,
  `condition_condition_id` INT(11) NOT NULL,
  PRIMARY KEY (`product_prod_id`, `condition_condition_id`),
  INDEX `fk_product_has_condition_condition1_idx` (`condition_condition_id` ASC) ,
  INDEX `fk_product_has_condition_product1_idx` (`product_prod_id` ASC) ,
  CONSTRAINT `fk_product_has_condition_product1`
    FOREIGN KEY (`product_prod_id`)
    REFERENCES `ambardb_model`.`product` (`prod_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_has_condition_condition1`
    FOREIGN KEY (`condition_condition_id`)
    REFERENCES `ambardb_model`.`condition` (`condition_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `ambardb_model`.`product_has_versions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ambardb_model`.`product_has_versions` ;

CREATE TABLE IF NOT EXISTS `ambardb_model`.`product_has_versions` (
  `product_prod_id` INT(11) NOT NULL,
  `versions_vers_id` INT(11) NOT NULL,
  PRIMARY KEY (`product_prod_id`, `versions_vers_id`),
  INDEX `fk_product_has_versions_versions1_idx` (`versions_vers_id` ASC) ,
  INDEX `fk_product_has_versions_product1_idx` (`product_prod_id` ASC) ,
  CONSTRAINT `fk_product_has_versions_product1`
    FOREIGN KEY (`product_prod_id`)
    REFERENCES `ambardb_model`.`product` (`prod_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_has_versions_versions1`
    FOREIGN KEY (`versions_vers_id`)
    REFERENCES `ambardb_model`.`versions` (`vers_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `ambardb_model`.`product_has_storage`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ambardb_model`.`product_has_storage` ;

CREATE TABLE IF NOT EXISTS `ambardb_model`.`product_has_storage` (
  `product_prod_id` INT(11) NOT NULL,
  `storage_storage_id` INT(11) NOT NULL,
  PRIMARY KEY (`product_prod_id`, `storage_storage_id`),
  INDEX `fk_product_has_storage_storage1_idx` (`storage_storage_id` ASC) ,
  INDEX `fk_product_has_storage_product1_idx` (`product_prod_id` ASC) ,
  CONSTRAINT `fk_product_has_storage_product1`
    FOREIGN KEY (`product_prod_id`)
    REFERENCES `ambardb_model`.`product` (`prod_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_has_storage_storage1`
    FOREIGN KEY (`storage_storage_id`)
    REFERENCES `ambardb_model`.`storage` (`storage_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `ambardb_model`.`product_has_size`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ambardb_model`.`product_has_size` ;

CREATE TABLE IF NOT EXISTS `ambardb_model`.`product_has_size` (
  `product_prod_id` INT(11) NOT NULL,
  `size_size_id` INT(11) NOT NULL,
  PRIMARY KEY (`product_prod_id`, `size_size_id`),
  INDEX `fk_product_has_size_size1_idx` (`size_size_id` ASC) ,
  INDEX `fk_product_has_size_product1_idx` (`product_prod_id` ASC) ,
  CONSTRAINT `fk_product_has_size_product1`
    FOREIGN KEY (`product_prod_id`)
    REFERENCES `ambardb_model`.`product` (`prod_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_has_size_size1`
    FOREIGN KEY (`size_size_id`)
    REFERENCES `ambardb_model`.`size` (`size_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `ambardb_model`.`product_has_power`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ambardb_model`.`product_has_power` ;

CREATE TABLE IF NOT EXISTS `ambardb_model`.`product_has_power` (
  `product_prod_id` INT(11) NOT NULL,
  `power_power_id` INT(11) NOT NULL,
  PRIMARY KEY (`product_prod_id`, `power_power_id`),
  INDEX `fk_product_has_power_power1_idx` (`power_power_id` ASC) ,
  INDEX `fk_product_has_power_product1_idx` (`product_prod_id` ASC) ,
  CONSTRAINT `fk_product_has_power_product1`
    FOREIGN KEY (`product_prod_id`)
    REFERENCES `ambardb_model`.`product` (`prod_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_has_power_power1`
    FOREIGN KEY (`power_power_id`)
    REFERENCES `ambardb_model`.`power` (`power_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `ambardb_model`.`product_has_model`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ambardb_model`.`product_has_model` ;

CREATE TABLE IF NOT EXISTS `ambardb_model`.`product_has_model` (
  `product_prod_id` INT(11) NOT NULL,
  `model_model_id` INT(11) NOT NULL,
  PRIMARY KEY (`product_prod_id`, `model_model_id`),
  INDEX `fk_product_has_model_model1_idx` (`model_model_id` ASC) ,
  INDEX `fk_product_has_model_product1_idx` (`product_prod_id` ASC) ,
  CONSTRAINT `fk_product_has_model_product1`
    FOREIGN KEY (`product_prod_id`)
    REFERENCES `ambardb_model`.`product` (`prod_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_has_model_model1`
    FOREIGN KEY (`model_model_id`)
    REFERENCES `ambardb_model`.`model` (`model_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `ambardb_model`.`product_has_voltage`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ambardb_model`.`product_has_voltage` ;

CREATE TABLE IF NOT EXISTS `ambardb_model`.`product_has_voltage` (
  `product_prod_id` INT(11) NOT NULL,
  `voltage_voltage_id` INT(11) NOT NULL,
  PRIMARY KEY (`product_prod_id`, `voltage_voltage_id`),
  INDEX `fk_product_has_voltage_voltage1_idx` (`voltage_voltage_id` ASC) ,
  INDEX `fk_product_has_voltage_product1_idx` (`product_prod_id` ASC) ,
  CONSTRAINT `fk_product_has_voltage_product1`
    FOREIGN KEY (`product_prod_id`)
    REFERENCES `ambardb_model`.`product` (`prod_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_has_voltage_voltage1`
    FOREIGN KEY (`voltage_voltage_id`)
    REFERENCES `ambardb_model`.`voltage` (`voltage_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `ambardb_model`.`country_has_state`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ambardb_model`.`country_has_state` ;

CREATE TABLE IF NOT EXISTS `ambardb_model`.`country_has_state` (
  `country_country_id` INT(11) NOT NULL,
  `state_state_id` INT(11) NOT NULL,
  PRIMARY KEY (`country_country_id`, `state_state_id`),
  INDEX `fk_country_has_state_state1_idx` (`state_state_id` ASC) ,
  INDEX `fk_country_has_state_country1_idx` (`country_country_id` ASC) ,
  CONSTRAINT `fk_country_has_state_country1`
    FOREIGN KEY (`country_country_id`)
    REFERENCES `ambardb_model`.`country` (`country_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_country_has_state_state1`
    FOREIGN KEY (`state_state_id`)
    REFERENCES `ambardb_model`.`state` (`state_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `ambardb_model`.`state_has_city`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ambardb_model`.`state_has_city` ;

CREATE TABLE IF NOT EXISTS `ambardb_model`.`state_has_city` (
  `state_state_id` INT(11) NOT NULL,
  `city_city_id` INT(11) NOT NULL,
  PRIMARY KEY (`state_state_id`, `city_city_id`),
  INDEX `fk_state_has_city_city1_idx` (`city_city_id` ASC) ,
  INDEX `fk_state_has_city_state1_idx` (`state_state_id` ASC) ,
  CONSTRAINT `fk_state_has_city_state1`
    FOREIGN KEY (`state_state_id`)
    REFERENCES `ambardb_model`.`state` (`state_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_state_has_city_city1`
    FOREIGN KEY (`city_city_id`)
    REFERENCES `ambardb_model`.`city` (`city_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `ambardb_model`.`city_has_address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ambardb_model`.`city_has_address` ;

CREATE TABLE IF NOT EXISTS `ambardb_model`.`city_has_address` (
  `city_city_id` INT(11) NOT NULL,
  `address_address_id` INT(11) NOT NULL,
  PRIMARY KEY (`city_city_id`, `address_address_id`),
  INDEX `fk_city_has_address_address1_idx` (`address_address_id` ASC) ,
  INDEX `fk_city_has_address_city1_idx` (`city_city_id` ASC) ,
  CONSTRAINT `fk_city_has_address_city1`
    FOREIGN KEY (`city_city_id`)
    REFERENCES `ambardb_model`.`city` (`city_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_city_has_address_address1`
    FOREIGN KEY (`address_address_id`)
    REFERENCES `ambardb_model`.`address` (`address_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `ambardb_model`.`user_has_address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ambardb_model`.`user_has_address` ;

CREATE TABLE IF NOT EXISTS `ambardb_model`.`user_has_address` (
  `user_usr_id` INT(11) NOT NULL,
  `address_address_id` INT(11) NOT NULL,
  PRIMARY KEY (`user_usr_id`, `address_address_id`),
  INDEX `fk_user_has_address_address1_idx` (`address_address_id` ASC) ,
  INDEX `fk_user_has_address_user1_idx` (`user_usr_id` ASC) ,
  CONSTRAINT `fk_user_has_address_user1`
    FOREIGN KEY (`user_usr_id`)
    REFERENCES `ambardb_model`.`user` (`usr_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_address_address1`
    FOREIGN KEY (`address_address_id`)
    REFERENCES `ambardb_model`.`address` (`address_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `ambardb_model`.`product_has_address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ambardb_model`.`product_has_address` ;

CREATE TABLE IF NOT EXISTS `ambardb_model`.`product_has_address` (
  `product_prod_id` INT(11) NOT NULL,
  `address_address_id` INT(11) NOT NULL,
  PRIMARY KEY (`product_prod_id`, `address_address_id`),
  INDEX `fk_product_has_address_address1_idx` (`address_address_id` ASC) ,
  INDEX `fk_product_has_address_product1_idx` (`product_prod_id` ASC) ,
  CONSTRAINT `fk_product_has_address_product1`
    FOREIGN KEY (`product_prod_id`)
    REFERENCES `ambardb_model`.`product` (`prod_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_has_address_address1`
    FOREIGN KEY (`address_address_id`)
    REFERENCES `ambardb_model`.`address` (`address_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
